"""add paystack_recipient_code to accounts

Revision ID: 90de3ac76b55
Revises: 8dd4c61098da
Create Date: 2026-04-30 23:04:00.335069

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "90de3ac76b55"
down_revision = "8dd4c61098da"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("paystack_recipient_code", sa.String(length=100), nullable=True),
    )
    op.create_index(
        op.f("ix_accounts_paystack_recipient_code"),
        "accounts",
        ["paystack_recipient_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_paystack_recipient_code"), table_name="accounts")
    op.drop_column("accounts", "paystack_recipient_code")
    # ### end Alembic commands ###
