"""Add product_price_id pin to checkout links

Revision ID: d0937a232997
Revises: 90de3ac76b55
Create Date: 2026-08-21 15:44:05.660405

"""

import sqlalchemy as sa
from alembic import op

# Polar Custom Imports

# revision identifiers, used by Alembic.
revision = "d0937a232997"
down_revision = "90de3ac76b55"
branch_labels: tuple[str] | None = None
depends_on: tuple[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkout_links", sa.Column("product_price_id", sa.Uuid(), nullable=True)
    )
    op.create_foreign_key(
        op.f("checkout_links_product_price_id_fkey"),
        "checkout_links",
        "product_prices",
        ["product_price_id"],
        ["id"],
        ondelete="set null",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("checkout_links_product_price_id_fkey"),
        "checkout_links",
        type_="foreignkey",
    )
    op.drop_column("checkout_links", "product_price_id")
    # ### end Alembic commands ###
